#!/bin/bash

rm -f translation_3.4.jar

mkdir -p build 2>/dev/null
cp -Rf translation_3.4/translation build/
find build/translation -type f -not -name '*.properties' -exec rm -f {} \;

cd translation_3.4
find translation -name '*.properties' -exec native2ascii {} ../build/{} \;
cd ..

java -cp K3Translator.jar:bcel-5.2.jar  Translator mt translation_3.4/translation translation_3.4.jar

cd build/translation
zip -r ../../translation_3.4.jar com
cd ../..

rm -Rf build/translation

rm -Rf build/trans_orig
rm -Rf build/trans_win
mkdir -p build/trans_orig 2>/dev/null
mkdir -p build/trans_win 2>/dev/null
cd build/trans_orig
ln -sf ../../translation_3.4.jar translation_3.4.jar
unzip translation_3.4.jar
find . -type f -not -name 'translation_*' -exec sh -c 'path=../trans_win/$(echo {} | tr "/" "\\" 2>/dev/null | sed "s/^.\\\//g"); echo $path; cp -f "{}" "$path"'   \;
cd ../trans_win/
zip translation.jar *
mv -f translation.jar ../../loc_hack/src/
cd ../..
ln -sf loc_hack/src/translation.jar translation.jar

rm -Rf translation_3.4/translation_jar/com
cp -lRf build/trans_orig/com translation_3.4/translation_jar/
